development:
  adapter: mysql2
  host: localhost
  database: workflow_development
  username: root
  password: qazplm123

external:
  adapter: postgresql
  host: localhost
  database: workflow_development
  username: postgres
  password: postgres
